### ISSUE TITLE
JavaScript Capstone

### ISSUE THREAD

**Issue by jorgeabrahan** [jorgeabrahan/javascript_capstone#21]
[GitHub project](https://github.com/jorgeabrahan/javascript_capstone/projects/1)

We are two members:
- Student A: Jorge Abrahan
- Student B: Edahi Gutierrez

**Comment by huseyinbiyik** [comment]
Hi @jorgeabrahan and @edahigure,

## ✔️ Status: APPROVED 🏆 🎉 🎊

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/wZjlCH43M3M0U/giphy.gif)



## Highlights
- All tasks are assigned 👍 
- Issue description is descriptive 📝

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
